[package]
name = "crates-feature-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
crates-index = "0.19.8"
crossterm = "0.26.1"
semver = "1.0.17"
toml = "0.7.3"
toml_edit = "0.19.8"

[[bin]]
name = "cargo-feature"
path = "src/main.rs"
