[package]
name = "cargo-features-manager"
version = "0.4.0"
edition = "2021"
authors = ["ToBinio"]
license = "MIT"
description = "A tui tool to enable & disable dependency features"
categories = ["command-line-utilities"]
repository = "https://github.com/ToBinio/cargo-features-manager"
keywords = ["cli", "manager", "cargo", "crates", "feature"]
homepage = "https://github.com/ToBinio/cargo-features-manager.git"
readme = "README.md"
rust-version = "1.64.0"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.13", features = ["help", "derive", "std"], default-features = false }
console = { version = "0.15.7", default-features = false }
crates-index = "2.4.0"
ctrlc = "3.4.1"
fuzzy-matcher = "0.3.7"
http = "1.0.0"
itertools = { version = "0.12.0", features = ["use_alloc"], default-features = false }
semver = { version = "1.0.21", default-features = false }
toml = { version = "0.8.8", default-features = false }
toml_edit = { version = "0.21.0", default-features = false }
ureq = { version = "2.9.1", features = ["http-interop"], default-features = false }

[[bin]]
name = "cargo-features"
path = "src/main.rs"
