[package]
name = "cargo-features-manager"
version = "0.2.0"
edition = "2021"
authors = ["ToBinio"]
license = "MIT"
description = "A cli tool to manage dependency features"
categories = ["command-line-utilities"]
exclude = ["/.idea", "/resources"]
repository = "https://github.com/ToBinio/cargo-features-manager"
keywords = ["cli", "manager", "cargo", "crates", "feature"]
homepage = "https://github.com/ToBinio/cargo-features-manager.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.70"
bitap = "0.2.0"
clap = { version = "4.2.4", features = ["derive"] }
crates-index = "0.19.8"
crossterm = "0.26.1"
ctrlc = "3.3.0"
levenshtein = "1.0.5"
semver = "1.0.17"
toml_edit = "0.19.8"

[[bin]]
name = "cargo-features"
path = "src/main.rs"
