[package]
name = "cargo-features-manager"
version = "0.1.0"
edition = "2021"
authors = ["ToBinio"]
edition = "2021"
license = "MIT"
description = "a cli tool to manage the features of your project dependencies"
categories = ["command-line-utilities"]
exclude = ["/.idea"]
repository = "https://github.com/ToBinio/cargo-features-manager"
keywords = ["cli", "manager", "cargo", "crates", "feature"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive"] }
crates-index = "0.19.8"
crossterm = "0.26.1"
semver = "1.0.17"
toml = "0.7.3"
toml_edit = "0.19.8"

[[bin]]
name = "cargo-features"
path = "src/main.rs"
