[package]
name = "crates-feature-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
crates-index = "0.19.8"
crossterm = { version = "0.26.1", features = ["event-stream", "filedescriptor"] }
toml = { version = "0.7.3", features = ["display", "parse"] }
toml_edit = "0.19.8"
